### ISSUE TITLE
CGO does not seem to work on golang:1.6-alpine

### ISSUE THREAD

**Issue by reasonerjt** [docker-library/golang#86]
I have a go install -a -v in my Dockerfile, and tried to run "docker build"

Initially I saw such error:
.....
\#runtime/cgo
exec: "gcc": executable file not found in $PATH
....

After adding "apk add gcc" into Dockerfile, I saw this error:
.....
\# runtime/cgo
/usr/local/go/src/runtime/cgo/cgo.go:54:19: fatal error: errno.h: No such file or directory
compilation terminated.
.....

**Comment by client9** [comment]
try adding musl-dev

Not sure why gcc doesnt depend on it.

```
/go # find /usr -name 'errno.h'
/go # apk add musl-dev
(1/1) Installing musl-dev (1.1.12-r2)
OK: 33 MiB in 20 packages
/go # find /usr -name 'errno.h'
/usr/include/sys/errno.h
/usr/include/bits/errno.h
/usr/include/errno.h
```

**Comment by reasonerjt** [comment]
Thanks @client9 , it works!
However I will keep this open to confirm with the maintainer regarding if this is a decision in design not to support cgo in this image.

**Comment by client9** [comment]
used to live in tokyo @reasonerjt   love your icon!

**Comment by yosifkit** [comment]
Yeah, the alpine images are designed to be minimal.
> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images
> \- https://github.com/docker-library/docs/tree/master/golang#golangalpine

**Comment by reasonerjt** [comment]
@client9 lol...
@yosifkit ok, closing.
